version: "3.9"
services:
  descriptor:
    build: .
    restart: always
    ports:
      - "5053:5053"
    environment:
      FLASK_ENV: development
    env_file:
      - .env
    volumes:
      - ./cert:/app/cert
      - ./data:/app/data
      - ./database:/app/database
      - ./sessions:/app/sessions