version: "3.9"
services:
  descriptor:
    build: .
    restart: always
    ports:
      - "5056:5056"
    environment:
      FLASK_ENV: development
    env_file:
      - .env
    volumes:
      - ./cert:/app/cert
      - ./data:/app/data