version: "3.9"
services:
  descriptor:
    build: .
    restart: always
    ports:
      - "5055:5055"
    environment:
      FLASK_ENV: development
    volumes:
      - ./cert:/app/cert
      - ./data:/app/data