"""empty message

Revision ID: 04f894dfe259
Revises: c0465a6373e0
Create Date: 2023-08-31 22:58:01.676650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f894dfe259'
down_revision = 'c0465a6373e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_props_faq', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_property_values_faq', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('include_properties_faq', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.drop_column('include_properties_faq')
        batch_op.drop_column('max_property_values_faq')
        batch_op.drop_column('max_props_faq')

    # ### end Alembic commands ###
