"""empty message

Revision ID: 12ef6f2cb66b
Revises: 2eedb9d33d07
Create Date: 2023-09-07 10:39:41.530984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ef6f2cb66b'
down_revision = '2eedb9d33d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_handle', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed', schema=None) as batch_op:
        batch_op.drop_column('url_handle')

    # ### end Alembic commands ###
