"""empty message

Revision ID: 15742f964660
Revises: c694aecabb11
Create Date: 2023-09-05 00:14:44.932563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15742f964660'
down_revision = 'c694aecabb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kill_process', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_category', schema=None) as batch_op:
        batch_op.drop_column('kill_process')

    # ### end Alembic commands ###
