"""empty message

Revision ID: 269e955ea0a9
Revises: 698e80ea9b50
Create Date: 2023-09-07 12:46:16.861257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269e955ea0a9'
down_revision = '698e80ea9b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed', schema=None) as batch_op:
        batch_op.drop_column('token_count')

    # ### end Alembic commands ###
