"""empty message

Revision ID: 2eedb9d33d07
Revises: 354515804d94
Create Date: 2023-09-07 10:32:26.641196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eedb9d33d07'
down_revision = '354515804d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed', schema=None) as batch_op:
        batch_op.drop_column('short_description')
        batch_op.drop_column('description')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')

    # ### end Alembic commands ###
