"""empty message

Revision ID: 31830b36394e
Revises: 89b1ea1b9d7a
Create Date: 2023-08-26 23:20:39.036437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31830b36394e'
down_revision = '89b1ea1b9d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.drop_column('category_url')

    # ### end Alembic commands ###
