"""empty message

Revision ID: 31c6e9f7d21b
Revises: e7f115a309d3
Create Date: 2023-08-24 00:18:09.351812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c6e9f7d21b'
down_revision = 'e7f115a309d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
