"""empty message

Revision ID: 4e4c75b0545c
Revises: afa908cab9b9
Create Date: 2023-09-04 15:24:38.826989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4c75b0545c'
down_revision = 'afa908cab9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.Boolean(), nullable=True))

    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.drop_column('category_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_updated', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.drop_column('updated')

    # ### end Alembic commands ###
