"""empty message

Revision ID: 54a40287e9fa
Revises: 4e4c75b0545c
Create Date: 2023-09-04 15:36:28.637008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a40287e9fa'
down_revision = '4e4c75b0545c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_ready', sa.Boolean(), nullable=True))
        batch_op.drop_column('updated')

    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_updated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.drop_column('category_updated')

    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('category_ready')

    # ### end Alembic commands ###
