"""empty message

Revision ID: 558aa509beef
Revises: eb0e80586a62
Create Date: 2023-08-29 18:30:34.443506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558aa509beef'
down_revision = 'eb0e80586a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faq_top_brands_links', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('faq_category_links', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('faq_use_schema', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('faq_include_category_name_at_headings', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('faq_brand_link_authority', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('faq_wiki_link_authority', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.drop_column('faq_wiki_link_authority')
        batch_op.drop_column('faq_brand_link_authority')
        batch_op.drop_column('faq_include_category_name_at_headings')
        batch_op.drop_column('faq_use_schema')
        batch_op.drop_column('faq_category_links')
        batch_op.drop_column('faq_top_brands_links')

    # ### end Alembic commands ###
