"""empty message

Revision ID: 63f6e756635d
Revises: 15742f964660
Create Date: 2023-09-05 14:32:40.308213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f6e756635d'
down_revision = '15742f964660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_additional_instructions', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.drop_column('enable_additional_instructions')

    # ### end Alembic commands ###
