"""empty message

Revision ID: 6ba09a0c778e
Revises: 7ea2b86b6022
Create Date: 2023-09-04 23:07:45.599492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba09a0c778e'
down_revision = '7ea2b86b6022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_category', schema=None) as batch_op:
        batch_op.drop_column('batch')

    # ### end Alembic commands ###
