"""empty message

Revision ID: 6ba2a8a79c5b
Revises: 
Create Date: 2023-08-22 17:39:43.882172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba2a8a79c5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_structure', sa.Text(), nullable=True))
        batch_op.drop_column('target_category_info')
        batch_op.drop_column('products_by_sales')
        batch_op.drop_column('best_selling_brands')
        batch_op.drop_column('category_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_info', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('best_selling_brands', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('products_by_sales', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('target_category_info', sa.TEXT(), nullable=True))
        batch_op.drop_column('category_structure')

    # ### end Alembic commands ###
