"""empty message

Revision ID: 7be81356c57a
Revises: 666be4eb62f9
Create Date: 2023-09-01 23:32:44.013669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be81356c57a'
down_revision = '666be4eb62f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.drop_column('only_active_products_faq')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('only_active_products_faq', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
