"""empty message

Revision ID: 7ea2b86b6022
Revises: 54a40287e9fa
Create Date: 2023-09-04 15:45:06.120593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea2b86b6022'
down_revision = '54a40287e9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_update', sa.Boolean(), nullable=True))
        batch_op.drop_column('category_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_updated', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('category_update')

    # ### end Alembic commands ###
