"""empty message

Revision ID: 89b1ea1b9d7a
Revises: 31c6e9f7d21b
Create Date: 2023-08-24 00:30:46.654876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b1ea1b9d7a'
down_revision = '31c6e9f7d21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_test_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.drop_column('category_test_mode')

    # ### end Alembic commands ###
