"""empty message

Revision ID: 90875343a588
Revises: 558aa509beef
Create Date: 2023-08-30 10:22:25.783332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90875343a588'
down_revision = '558aa509beef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.drop_column('threshold_lenght')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold_lenght', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
