"""empty message

Revision ID: 98b354a2a008
Revises: 12ef6f2cb66b
Create Date: 2023-09-07 11:26:29.640554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b354a2a008'
down_revision = '12ef6f2cb66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_category', schema=None) as batch_op:
        batch_op.drop_column('published')

    # ### end Alembic commands ###
