"""empty message

Revision ID: a1b4b43744a4
Revises: b3d3a289171d
Create Date: 2023-08-31 23:57:46.517366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b4b43744a4'
down_revision = 'b3d3a289171d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_category_name_at_headings', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.drop_column('include_category_name_at_headings')

    # ### end Alembic commands ###
