"""empty message

Revision ID: acc56cba268c
Revises: c7be578446cd
Create Date: 2023-08-27 01:15:41.316034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc56cba268c'
down_revision = 'c7be578446cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.alter_column('use_main_keywords',
               existing_type=sa.BOOLEAN(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.alter_column('use_main_keywords',
               existing_type=sa.Text(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
