"""empty message

Revision ID: b3d3a289171d
Revises: 04f894dfe259
Create Date: 2023-08-31 23:46:52.669479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d3a289171d'
down_revision = '04f894dfe259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.drop_column('include_category_name_at_headings')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_category_name_at_headings', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
