"""empty message

Revision ID: baf339f46bdc
Revises: acc56cba268c
Create Date: 2023-08-29 01:12:23.879990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf339f46bdc'
down_revision = 'acc56cba268c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_faq_info', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('add_top_brands_faq', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('add_best_selling_products_faq', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('only_active_products_faq', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_category_info_faq', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('additional_instructions_faq', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.drop_column('additional_instructions_faq')
        batch_op.drop_column('include_category_info_faq')
        batch_op.drop_column('only_active_products_faq')
        batch_op.drop_column('add_best_selling_products_faq')
        batch_op.drop_column('add_top_brands_faq')
        batch_op.drop_column('include_faq_info')

    # ### end Alembic commands ###
