"""empty message

Revision ID: c694aecabb11
Revises: dad24b331509
Create Date: 2023-09-04 23:39:07.211318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c694aecabb11'
down_revision = 'dad24b331509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_category', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
