"""empty message

Revision ID: eb0e80586a62
Revises: a929da8f05b3
Create Date: 2023-08-29 17:49:52.790292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0e80586a62'
down_revision = 'a929da8f05b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_seo_faq_package', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_settings', schema=None) as batch_op:
        batch_op.drop_column('use_seo_faq_package')

    # ### end Alembic commands ###
